### ISSUE TITLE
how to make pushed down footer

### ISSUE THREAD

**Issue by gurumark** [maddisondesigns/Quark#13]
Great theme! Is there any way to push footer down to the screen bottom using css?

**Comment by maddisondesigns** [comment]
Thanks. If you want the footer to stick to the bottom of the screen, I'd suggest having a read through this post on CSS Tricks - https://css-tricks.com/snippets/css/sticky-footer/

**Comment by gurumark** [comment]
Unfortunately, It did not work for me. Here is what I did using Quark's css:

#wrapper {
  min-height: 100%;
  /* equal to footer height */
  margin-bottom: -60px; 
}
#wrapper:after {
  content: "";
  display: block;
}
#footercontainer, #wrapper:after {
  height: 60px; 
}
Am I missing anything here? Thanks much for your help. I know you closed this issue but I do not want to use another theme.
