### ISSUE TITLE
Skip link for screen readers is broken

### ISSUE THREAD

**Issue by skorasaurus** [maddisondesigns/Quark#18]
Hi, 

First off, thanks for making this; I'm considering using Quark as a parent theme for a website. 

I wanted to let you know that the skip-link doesn't function; I couldn't get it to tirgger on a vanilla wordpress site (I made only one test post on it; nothing else customized). 

It appears several things need to be fixed for it to work: 
there are two skip links seem to be coded in header.php - https://github.com/skorasaurus/Quark/blob/8e81c5da94788ad685632b142277552d68f0a07f/header.php#L41 directs to #content which isn't referenced anywhere else in the repo. 

and https://github.com/skorasaurus/Quark/blob/8e81c5da94788ad685632b142277552d68f0a07f/header.php#L67 which does direct to #primary which is used on many templates. This appears a little late, after the social media icons in the nav, and probably should be moved to the beginning of header.php (probably replace line 41). 

Also consider removing the skip-link class since its not defined in your css; 

Lastly, the screen-reader-text CSS recommended for use in WP themes was updated a couple years ago to match best practices; more recently than you had last edited it. You can find an example at https://github.com/WordPress/twentynineteen/blob/e74d348ab9cfc6ad46bdf33f691611930c39e944/style.css#L1875 

Also see https://make.wordpress.org/accessibility/handbook/markup/the-css-class-screen-reader-text/

**Comment by maddisondesigns** [comment]
Thanks for your PR to fix these issues. Much appreciated 😄

**Comment by maddisondesigns** [comment]
I have another theme in the Theme Directory called [Ephemeris](https://wordpress.org/themes/ephemeris/), which is also a lightweight starter theme. It's newer than quark and has some better functionality like proper Customizer options, and I've also added better compatibility for the new Block Editor. I just thought I'd mention it in case you want to check it out. You can view demo [over here](http://demo.skyrocketthemes.com/ephemeris/).
